
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-mini-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: devops-mini.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: devops-mini-svc
              port:
                number: 5000